### ISSUE TITLE
Laravel Vapor Error

### ISSUE THREAD

**Issue by c-fitzmaurice** [stepanenko3/nova-command-runner#5]
Hello, this Nova plugin is great, but it seems to be getting tripped up on Vapor. I've tried several patches and override of the routes files but have been unsuccessful. Wanted to see if you had any insight. Thanks!

## Error

Your serialized closure might have been modified or it's unsafe to be unserialized.

## Stack Trace

```
#0 [internal function]: Laravel\SerializableClosure\Serializers\Signed-&gt;__unserialize(Array)
#1 /var/task/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(23): unserialize(&#039;O:47:&quot;Laravel\\S...&#039;)
#2 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Route.php(527): Illuminate\Routing\RouteSignatureParameters::fromAction(Array, Array)
#3 /var/task/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(78): Illuminate\Routing\Route-&gt;signatureParameters(Array)
#4 /var/task/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(28): Illuminate\Routing\ImplicitRouteBinding::resolveBackedEnumsForRoute(Object(Illuminate\Routing\Route), Array)
#5 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Router.php(874): Illuminate\Routing\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Route))
#6 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Router-&gt;substituteImplicitBindings(Object(Illuminate\Routing\Route))
#7 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /var/task/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/task/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/task/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#14 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/task/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/task/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#21 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#23 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#25 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /var/task/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Nova\Http\Middleware\ServeNova-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/task/vendor/laravel/vapor-core/src/Http/Middleware/ServeStaticAssets.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Vapor\Http\Middleware\ServeStaticAssets-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/task/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/task/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/task/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustHosts.php(48): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustHosts-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#48 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /var/task/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#50 /var/task/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway-&gt;handle(Object(Illuminate\Http\Request))
#51 /var/task/vendor/laravel/vapor-core/src/Runtime/Octane/Octane.php(194): Laravel\Octane\Worker-&gt;handle(Object(Illuminate\Http\Request), Object(Laravel\Octane\RequestContext))
#52 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Vapor\Runtime\Octane\Octane::Laravel\Vapor\Runtime\Octane\{closure}(Object(Illuminate\Http\Request))
#53 /var/task/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureBinaryEncoding.php(19): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Vapor\Runtime\Http\Middleware\EnsureBinaryEncoding-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/task/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureVanityUrlIsNotIndexed.php(16): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Vapor\Runtime\Http\Middleware\EnsureVanityUrlIsNotIndexed-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/task/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/RedirectStaticAssets.php(30): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Vapor\Runtime\Http\Middleware\RedirectStaticAssets-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/task/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureOnNakedDomain.php(46): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Vapor\Runtime\Http\Middleware\EnsureOnNakedDomain-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/task/vendor/laravel/vapor-core/src/Runtime/Octane/Octane.php(197): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#63 /var/task/vendor/laravel/vapor-core/src/Runtime/Octane/Octane.php(162): Laravel\Vapor\Runtime\Octane\Octane::sendRequest(Object(Illuminate\Http\Request), Object(Laravel\Octane\RequestContext))
#64 /var/task/vendor/laravel/vapor-core/src/Runtime/Handlers/OctaneHandler.php(26): Laravel\Vapor\Runtime\Octane\Octane::handle(Object(Illuminate\Http\Request))
#65 /var/task/octaneRuntime.php(87): Laravel\Vapor\Runtime\Handlers\OctaneHandler-&gt;handle(Array)
#66 /var/task/vendor/laravel/vapor-core/src/Runtime/LambdaRuntime.php(53): {closure}(&#039;ec96437a-69ad-4...&#039;, Array)
#67 /var/task/octaneRuntime.php(89): Laravel\Vapor\Runtime\LambdaRuntime-&gt;nextInvocation(Object(Closure))
#68 /var/task/runtime.php(33): require(&#039;/var/task/octan...&#039;)
#69 /opt/bootstrap.php(6): require(&#039;/var/task/runti...&#039;)
#70 {main}
```

**Comment by stepanenko3** [comment]
Fixed in [v4.1.3](https://github.com/stepanenko3/nova-command-runner/releases/tag/v4.1.3)

@c-fitzmaurice, huge thanks
